#!/system/bin/env bash
# Coded by Ivam3 on Ago 2018
set -euo pipefail
IFS=$'\n\t'
#Var
	R='\033[1;31m'
        G='\033[1;32m'
        Y='\033[1;33m'
        B='\033[1;34m'
        M='\033[1;35m'
        C='\033[1;36m'
        W='\033[0m'
	arm=$(find $PREFIX/share/ -name "jdk8_arm.tar.gz" -type f)
	aarch=$(find $PREFIX/share/ -name "jdk8_aarch64.tar.gz" -type f)
	EMBED=$HOME/embed
	USR=$(whoami)

trap ctrl_c 2
function ctrl_c () {
	echo
	printf "$Y [!]$R Going me on https://t.me/Ivam3byCinderella$W
	\n"
}
function Chao_chao {
	echo "
        "
        printf "$C"
        echo "#-----THANKS TO MY MASTER CINDERELLA-----#"
        echo "#                                        #"
        echo "#             People don't die           #"
        echo "#    If they still live in the hearts    #"
        echo "#           of their loved ones          #"
        echo "#       We love her ... We miss her      #"
        echo "#                                        #"
        echo "#-------------------RIP------------------#"
        printf "$W"
	echo "
        "
}
testing() {
	testjava=$(command -v java)
	testembed=$(command -v EMBED)
	testapktool=$(command -v apktool)
	testsignapk=$(command -v signapk)
	testapksigner=$(command -v apksigner)
printf "$Y[!]-> Testing installation . . .\n"
sleep 1
printf "$W Java         "
sleep 1
if [ ! -z $testjava ]; then
        printf "$G > OK!!\n"
else
        printf "$R > ERROR$W\n"
fi
printf "$W Apktool      "
sleep 1
if [ ! -z $testapktool ]; then
        printf "$G > OK!!\n"
else
        printf "$R > ERROR$W\n"
fi
printf "$W Signapk      "
sleep 1
if [ ! -z $testsignapk ]; then
        printf "$G > OK!!\n"
else
        printf "$R > ERROR$W\n"
fi
printf "$W Apksigner    "
sleep 1
if [ ! -z $testapksigner ]; then
        printf "$G > OK!!\n"
else
        printf "$R > ERROR$W\n"
fi
printf "$W EMBED                "
sleep 1
if [ ! -z $testembed ]; then
        printf "$G > OK!!\n"
else
        printf "$R > ERROR$W\n"
fi
printf "$W Arg -x	"
sleep 1
if [ -e $PREFIX/opt/metasploit-framework/lib/msf/core/payload/apk.rb ]; then
	printf "$G > OK!!\n"
else
	printf "$R > ERROR$W\n"
fi
sleep 2
}
	echo $(clear)
        printf "$C"
        echo "         -{ IbyC > fix-arg-x } "
        echo "   -{ SO > Android - Only for Termux } "
        echo "              -{ Coded by } "
        printf "$G"
        echo "      =============================="
        echo "      .___.                 ______,"
        echo "      |   |__ ______   ___  \_____ \ "
        echo "      |   \ \/ /\__ \ /   \   _(__ <,"
	echo "      |   |\   / __ \| Y Y \ /      \ "       
	echo "      |___| \_/ (____|__|_| /______ /"
        echo "                     \/    \/      \/ "
        echo "      ====== By ___ Cinderella ======"
	echo
printf "$C"
        echo "          [---] Join me on [---]"
        echo "[-] www.youtube.com/c/ivam3bycinderella [-]"
        echo "            [-] t.me/ivam3 [-]"
        sleep 1
printf "$R"
        echo
        echo "          [---] DISCLAIMER [---]"
printf "$W"
        echo " This file fix issues in Metasploit Framework"
        echo "  in argument '-x' to get embed payload into"
	echo "               legitim apk
	\n"
        echo " If the law is violated with it's use,"
        echo "  This would be the responsibility of "
        echo "        the user who handled it"
printf "$R       [-] Use At Your Own Risk [-]"
        echo
        echo
	printf "        $C Press$G enter$C to continue$W"
	read enter
	echo "
	"
printf "$Y [!]$C Cleaning up . . .$W
\n"
	if [ -d $HOME/java ]; then
		rm -rf $HOME/java
	fi
	if [ -L $PREFIX/bin/signapk ]; then
                rm $PREFIX/bin/signapk
        fi
        if [ -L $PREFIX/bin/zzipalign ]; then
                rm $PREFIX/bin/zzipalign
        fi
	if [ -L $PREFIX/bin/apktool ]; then
                rm $PREFIX/bin/apktool
        fi
	if [ -L $PREFIX/bin/java ] || [ -e $PREFIX/bin/java ]; then
                rm $PREFIX/bin/java
        fi
	if [ -L $PREFIX/bin/EMBED ] || [ -e $PREFIX/bin/EMBED ]; then
                rm $PREFIX/bin/EMBED
        fi
	if [ -e $PREFIX/bin/sudo ] || [ -d $HOME/.suroot ]; then
		sudo chown -R $USR:$USR $HOME/.suroot
	fi

msf=$(find $PREFIX/opt/ -name "metasploit-framework" -type d)
	
	if [ -z $msf ]; then
		printf "$Y[W]$R metasploit framework it doesn't exist , please install it before$W\n"
		Chao_chao
	else
		printf "$Y[!]$C Upgrading && Downloading packages . . .$W\n"
		pkg update -y && pkg upgrade -y
		pkg install git wget axel tar apksigner aapt -y
	fi

printf "$Y [!]$C Creating directories . . .$W
\n"
git clone https://github.com/ivam3/java.git
TMP_DIR=$HOME/java
mkdir -p $TMP_DIR/handler
mkdir -p $TMP_DIR/unsign
mkdir -p $TMP_DIR/finished
printf "$Y\n\n[!]$C Downloading files . . .$W\n"
axel https://raw.githubusercontent.com/ivam3/embed/master/EMBED -o $PREFIX/bin/EMBED
wget https://raw.githubusercontent.com/ivam3/embed/master/set-apktool -O $PREFIX/bin/chapktool
chmod -R 711 $TMP_DIR
chmod 777 $PREFIX/bin/EMBED
chmod 777 $PREFIX/bin/chapktool
printf "$Y\n\n[!]$C Downloading binaries . . .$W\n"
bash $TMP_DIR/Ivam3
mv $msf/lib/msf/core/payload/apk.rb $msf/lib/msf/core/payload/apk.rb.O
curl https://raw.githubusercontent.com/ivam3/java/master/.embed/apk.rb -o $msf/lib/msf/core/payload/apk.rb
curl https://raw.githubusercontent.com/ivam3/java/master/.embed/signapk -o $PREFIX/bin/signapk
chmod 777 $PREFIX/bin/signapk
chmod 777 $msf/lib/msf/core/payload/apk.rb

	if [ -d $EMBED ]; then
		rm -rf $EMBED
	fi
#	if [ -f $arm ] || [ -f $aarch ]; then
printf "$C"
Chao_chao
sleep 1
testing
cd $HOME
echo ""
if [ ! -z $testjava ] && [ ! -z $testembed ] && [ ! -z $testapktool ] && [ ! -z $testsignapk ] && [ ! -z $testapksigner ]; then
	printf "$Y[IbyC]$C Finish !!$W \n \t Now you can hide a metasploit payload in legitim .APK \n \t \t Now try it by executing the command$G => EMBED$W\n\n"
	printf "$Y[!]$W If something was wrong, JOIN me on =>$B https://t.me/Ivam3_Bot$W\n\n"
else
	printf "$R"
	printf "$R[W]$W O-ops!! Something was wrong\n"
	printf "$Y[!]$W Please take screenshot of the error\nand send it to my bot in telegram \n $Y >>$B https://t.me/Ivam3_Bot$W\n\n"
fi
if [ -f $arm ]; then
	rm -rf $arm
fi
if [ -f $aarch ]; then
	rm -rf $aarch
fi
#						@IbyC.
