#!/data/data/com.termux/files/usr/bin/bash

#Colors
        R='\033[1;31m'
        G='\033[1;32m'
        Y='\033[1;33m'
        B='\033[1;34m'
        M='\033[1;35m'
        C='\033[1;36m'
        W='\033[0m'
	APKTOOLv=$(apktool -version)

                echo $(clear)
        printf "$C"
                echo "          -{> Apktool for EMBED <} "
                echo "   -{ SO > Android - Andrax && Termux } "
                echo "             -{ Adapted by } "
                printf "$G"
                echo "      =============================="
                echo "      .___.                 ______,"
                echo "      |   |__ ______   ___  \_____ \ "
                echo "      |   \ \/ /\__ \ /   \   _(__ <,"
                echo "      |   |\   / __ \| Y Y \ /      \ "
                echo "      |___| \_/ (____|__|_| /______ /"
                echo "                     \/    \/      \/ "
                echo "      ====== By ___ Cinderella ======"
        printf "$C\n"
                echo "          [---] Join me on [---]"
                echo "[-] www.youtube.com/c/ivam3bycinderella [-]"
                echo "      [-] t.me/Ivam3byCinderella [-]"
                echo "            [-] t.me/ivam3 [-]"
        printf "$R\n"
                echo "          [---] README.md [---]"
        printf "$W"
                echo " This file will change the configuration on"
                echo "    EMBED for Termux to testing with all"
                echo "        available apktools versions"
		echo
		echo " I will to change your apktool version and i"
		echo "  will to install a diferent version to fix"
		echo "       the uncompatibility with some "
		echo "               arquitecture"
		echo "
		"
        printf "$C         Press$G ENTER$C to continue"
        printf "$W\n"
        read enter
until [ $OPC > 8 ]; do
	printf "$G[-] CHOOSE AN APKTOOL VERSION TO INSTALL\n\n[1]:->$W 2.2.2\n$G[2]:->$W 2.2.3\n$G[3]:->$W 2.2.4\n$G[4]:->$W 2.3.0\n$G[5]:->$W 2.3.1\n$G[6]:->$W 2.3.2\n$G[7]:->$W 2.3.3\n$G[8]:->$W 2.3.4\n$G[0]:->$W Show your version\n\n$G"
		read -p ">> " OPC
	done
case $OPC in
	1)
		rm $PREFIX/var/spool/apktool.jar
		cp ~/java/openjdk/apktool_jar/apktool-2.2.2.jar $PREFIX/var/spool/apktool.jar
		printf "\n\n$G[-] ... DONE!!\n\t$W Now you can testing the apktool$Y v.$APKTOOLv $W runing$Y EMBED\n\n$W"
		;;
	2)
		rm $PREFIX/var/spool/apktool.jar
		cp ~/java/openjdk/apktool_jar/apktool_2.2.3.jar $PREFIX/var/spool/apktool.jar
		printf "\n\n$G[-] ... DONE!!\n\t$W Now you can testing the apktool$Y v.$APKTOOLv $W runing$Y EMBED\n\n$W"
		;;
	3)
		rm $PREFIX/var/spool/apktool.jar
		cp ~/java/openjdk/apktool_jar/apktool_2.2.4.jar $PREFIX/var/spool/apktool.jar
		printf "\n\n$G[-] ... DONE!!\n\t$W Now you can testing the apktool$Y v.$APKTOOLv $W runing$Y EMBED\n\n$W"
		;;
	4)
		rm $PREFIX/var/spool/apktool.jar
		cp ~/java/openjdk/apktool_jar/apktool_2.3.0.jar $PREFIX/var/spool/apktool.jar
		printf "\n\n$G[-] ... DONE!!\n\t$W Now you can testing the apktool$Y v.$APKTOOLv $W runing$Y EMBED\n\n$W"
		;;
	5)
		rm $PREFIX/var/spool/apktool.jar
		cp ~/java/openjdk/apktool_jar/apktool_2.3.1.jar $PREFIX/var/spool/apktool.jar
		printf "\n\n$G[-] ... DONE!!\n\t$W Now you can testing the apktool$Y v.$APKTOOLv $W runing$Y EMBED\n\n$W"
		;;
	6)
		rm $PREFIX/var/spool/apktool.jar
		cp ~/java/openjdk/apktool_jar/apktool_2.3.2.jar $PREFIX/var/spool/apktool.jar
		printf "\n\n$G[-] ... DONE!!\n\t$W Now you can testing the apktool$Y v.$APKTOOLv $W runing$Y EMBED\n\n$W"
		;;
	7)
		rm $PREFIX/var/spool/apktool.jar
		cp ~/java/openjdk/apktool_jar/apktool_2.3.3.jar $PREFIX/var/spool/apktool.jar
		printf "\n\n$G[-] ... DONE!!\n\t$W Now you can testing the apktool$Y v.$APKTOOLv $W runing$Y EMBED\n\n$W"
		;;
	8)
		rm $PREFIX/var/spool/apktool.jar
		cp ~/java/openjdk/apktool_jar/apktool_2.3.4.jar $PREFIX/var/spool/apktool.jar
		printf "\n\n$G[-] ... DONE!!\n\t$W Now you can testing the apktool$Y v.$APKTOOLv $W runing$Y EMBED\n\n$W"
		;;
	0)
		printf "\n\n$R[!] Your have install the apktool version :->$Y $APKTOOLv\n$W\n"
		;;
esac
